radicle:
  security:
    enable-csrf: false
  lsat:
    paths: buy-now,purchase
    lsat-server: http://api.radicle.local/lsat/v1/invoice
    lsat-verify: http://docker.for.mac.localhost/lsat/v1/verify
  mongo:
    user: radicle
    password: rad1cle
    mongoIp: mongodb://mongodb
    mongoPort: 27017
    mongoDbName: assets
application:

---

spring:
   profiles: test
application:

---

spring:
    profiles: docker-dev
application:

---

spring:
    profiles: staging
application:

---

spring:
    profiles: production
application:
radicle:
  lsat:
    lsat-server: https://api.radicle.vote/lsat/v1/invoice
    lsat-verify: https://api.radicle.vote/lsat/v1/verify
   