radicle:
  security:
    enable-csrf: false
  lsat:
    paths: buy-now,purchase
    lsat-server: http://api.risidio.local/lsat/v1/invoice
    address-server: http://docker.for.mac.localhost/lsat/v1/bitcoin-address
    lsat-verify: http://docker.for.mac.localhost/lsat/v1/verify
  mongo:
    mongoIp: mongodb://mongodb
    mongoPort: 27017
    mongoDbName: assets
application:

---

spring:
   profiles: test
application:

---

spring:
    profiles: docker-dev
application:
radicle:
  lsat:
    lsat-server: https://api.risidio.com/lsat/v1/invoice
    lsat-verify: https://api.risidio.com/lsat/v1/verify
    address-server: http://api.risidio.com/lsat/v1/bitcoin-address

---

spring:
    profiles: staging
application:

---

spring:
    profiles: production
application:
radicle:
  lsat:
    lsat-server: https://api.risidio.com/lsat/v1/invoice
    lsat-verify: https://api.risidio.com/lsat/v1/verify
    address-server: http://api.risidio.com/lsat/v1/bitcoin-address
   