security:
  oauth2:
    resource:
      token-info-uri: http://api.radicle.local/mesh/oauth2/introspect
spring:
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://login.assets.local/auth/realms/radiclesociety/protocol/openid-connect/token/introspect
          introspection-client-id: client
          introspection-client-secret: secret
application:
   mongoIp: mongodb://localhost
   mongoPort: 27017
   mongoDbName: assets

---

spring:
   profiles: test
application:
   mongoIp: mongodb://localhost

---

spring:
    profiles: docker-dev
application:
   mongoIp: mongodb://localhost

---

spring:
    profiles: staging
application:
   mongoIp: mongodb://mongodb

---

spring:
    profiles: production
application:
   mongoIp: mongodb://mongodb
