radicle:
  security:
    enable-csrf: false
  lsat:
    paths: buy-now,purchase
    lsat-server: http://api.radicle.local/lsat/v1/invoice
application:
   mongoIp: mongodb://localhost
   mongoPort: 27017
   mongoDbName: assets

---

spring:
   profiles: test
application:
   mongoIp: mongodb://localhost

---

spring:
    profiles: docker-dev
application:
   mongoIp: mongodb://localhost

---

spring:
    profiles: staging
application:
   mongoIp: mongodb://mongodb

---

spring:
    profiles: production
application:
   mongoIp: mongodb://mongodb
